---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'build/**'
      - 'contrib/**'
      - 'doc/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'build/**'
      - 'contrib/**'
      - 'doc/**'
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iconv: [enabled, disabled]
    steps:
      - id: checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt install -y --no-install-recommends \
            meson \
            ccache \
            libmpdclient-dev \
            check

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: linux-iconv=${{ matrix.iconv }}

      - name: Configure
        run: |
          meson setup \
            -Ddocumentation=disabled \
            -Dtest=true \
            -Diconv=${{ matrix.iconv }} \
            --wrap-mode nofallback \
            ${{ matrix.meson_options }} \
            output

      - name: Build
        run: meson compile -C output --verbose

      - name: Unit Tests
        run: meson test -C output --print-errorlogs

  build-macos:
    runs-on: macos-latest
    steps:
      - id: checkout
        uses: actions/checkout@v5

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: macos

      - uses: actions/setup-python@v6

      - name: Install dependencies
        run: |
          brew install \
            meson ninja \
            libmpdclient \
            check

      - name: Configure
        run: |
          meson setup \
            -Ddocumentation=disabled \
            -Dtest=true \
            --wrap-mode nofallback \
            ${{ matrix.meson_options }} \
            output

      - name: Build
        run: meson compile -C output --verbose

      - name: Unit Tests
        run: meson test -C output --print-errorlogs

  build-windows:
    runs-on: windows-latest
    steps:
      - id: checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          pip install meson ninja

      - name: Configure
        run: meson setup -Ddocumentation=disabled --wrap-mode forcefallback ${{ matrix.meson_options }} output

      - name: Build
        run: meson compile -C output --verbose

  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - id: checkout
        uses: actions/checkout@v5

      - name: Add VisualStudio command line tools into path
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: |
          pip install meson ninja

      - name: Configure
        run: meson setup -Ddocumentation=disabled --wrap-mode forcefallback ${{ matrix.meson_options }} output

      - name: Build
        run: meson compile -C output --verbose
